# speed control
[ add speed -0.25
] add speed 0.25
# speed = 1.0 with backspace

# volume control
UP add volume 10
DOWN add volume -10
WHEEL_UP add volume 10
WHEEL_DOWN add volume -10

# Resize with the keyboard
ALT+UP add window-scale 0.05
ALT+DOWN add window-scale -0.05
