#fullscreen enable on start
fs=yes

#default speed
speed=1.5

#default volume
volume=40

# limits mpv to 90% of your screen and keeps the video’s aspect ratio intact
 autofit-larger=90%x90%
 keepaspect-window=yes
