#fullscreen enable on start
fs=yes

#default speed
speed=1.5

#default volume
volume=40

# limits mpv to 90% of your screen and keeps the video’s aspect ratio intact
 autofit-larger=90%x90%
 keepaspect-window=yes


# sub-font-size=42 #to make subtitles larger.

# sub-scale=1.2 #to scale subtitles.

# save-position-on-quit=yes #to resume where you stopped.
